##### For extracting images from zip file

In [1]:
import shutil
shutil.unpack_archive("Images.zip")

In [2]:
# %pip install tensorflow

In [3]:
import pandas as pd
import os
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

2025-10-12 10:55:31.550545: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [4]:
labels_df = pd.read_csv("labels.csv", sep=",", header=None)

In [5]:
labels_df.head()

   0                  1    2   3    4    5
0  0       pickup_truck  213  34  255   50
1  0                car  194  78  273  122
2  0                car  155  27  183   35
3  0  articulated_truck   43  25  109   55
4  0                car  106  32  124   45

In [6]:
labels_df.columns = ['image_id', 'class', 'xmin', 'ymin', 'xmax', 'ymax']

In [7]:
labels_df.head(20)

    image_id              class  xmin  ymin  xmax  ymax
0          0       pickup_truck   213    34   255    50
1          0                car   194    78   273   122
2          0                car   155    27   183    35
3          0  articulated_truck    43    25   109    55
4          0                car   106    32   124    45
5          1                bus   205   155   568   314
6          1                bus   285   123   477   168
7          1                car   544   162   617   193
8          1                car   329   152   371   163
9          1                car   447   161   497   183
10         1                car   662   199   715   236
11         2  motorized_vehicle   334   362   603   479
12         3                car   480    99   511   120
13         3                car   257   199   369   280
14         4                bus   439    32   719   171
15         5                car   561    85   605   129
16         5  articulated_truck   132     3   712   254
17         6                car    22   135   136   204
18         7                car   471   175   708   386
19         8       pickup_truck   471   131   702   249

In [8]:
labels_df["image_id"] = labels_df["image_id"].apply(lambda x:f"{x:08d}")

In [9]:
labels_df.head(7)

   image_id              class  xmin  ymin  xmax  ymax
0  00000000       pickup_truck   213    34   255    50
1  00000000                car   194    78   273   122
2  00000000                car   155    27   183    35
3  00000000  articulated_truck    43    25   109    55
4  00000000                car   106    32   124    45
5  00000001                bus   205   155   568   314
6  00000001                bus   285   123   477   168

##### Loading first 1000 images into array names images

In [10]:
labels_df = labels_df.iloc[:1000]


images_dir = "Images/"

images228 = []
images480 = []

for index, row in labels_df.iterrows():
    img_path = os.path.join(images_dir, f"{row['image_id']}.jpg")
    img = cv2.imread(img_path)
    if img is not None:
        if len(img) == 228:
            images228.append(img)
        else:
            images480.append(img)
    else:
        print(f"Image {img_path} not found or could not be opened.")

In [11]:
len(images228) + len(images480)

1000

In [12]:
images228 = np.array(images228)

In [13]:
images480 = np.array(images480)

In [14]:
if len(images228) ==0:
    print("No images with height 228 found.")
else:
    print(f"Images with height 228 shape: {images228.shape} count: {len(images228)}")

Images with height 228 shape: (206, 228, 342, 3) count: 206

In [15]:
if len(images480) ==0:
    print("No images with height 228 found.")
else:
    print(f"Images with height 228 shape: {images480.shape} count: {len(images480)}")
    print(f"{len(images480)} images loaded successfully ")

Images with height 228 shape: (794, 480, 720, 3) count: 794
794 images loaded successfully

In [16]:
## Analyze the distribution of vehicle types in the dataset
vehicle_types = labels_df['class'].value_counts()
print(vehicle_types)

class
car                      682
pickup_truck             111
motorized_vehicle         61
articulated_truck         30
work_van                  29
bus                       28
pedestrian                23
single_unit_truck         18
bicycle                   12
non-motorized_vehicle      5
motorcycle                 1
Name: count, dtype: int64

In [17]:
if len(images228)>0:
    processed_images = [cv2.resize(img, (224, 224)) for img in images228]

In [18]:
if len(images480)>0:
    processed_images += [cv2.resize(img, (224, 224)) for img in images480]

In [34]:
print(len(processed_images))
print(processed_images[0].shape)
type(processed_images)

1000
(224, 224, 3)

numpy.ndarray

In [ ]:
# processed_images = np.array(processed_images)
# type(processed_images)

numpy.ndarray

In [35]:
len(processed_images)

1000

In [21]:
labels_df.head()

   image_id              class  xmin  ymin  xmax  ymax
0  00000000       pickup_truck   213    34   255    50
1  00000000                car   194    78   273   122
2  00000000                car   155    27   183    35
3  00000000  articulated_truck    43    25   109    55
4  00000000                car   106    32   124    45

In [22]:
labels  = labels_df['class'].to_numpy()
bounding_boxes = labels_df[['xmin', 'ymin', 'xmax', 'ymax']].to_numpy()

In [23]:
print(labels[3])

articulated_truck

In [24]:
bounding_boxes[3]

array([ 43,  25, 109,  55])

In [25]:
np.unique(labels)

array(['articulated_truck', 'bicycle', 'bus', 'car', 'motorcycle',
       'motorized_vehicle', 'non-motorized_vehicle', 'pedestrian',
       'pickup_truck', 'single_unit_truck', 'work_van'], dtype=object)

In [26]:
# # Concert lables to numerical values : One Hot Encoding
# from sklearn.preprocessing import OneHotEncoder
# encoder = OneHotEncoder(sparse_output=False)
# labels_encoded = encoder.fit_transform(labels.reshape(-1, 1))
# labels_encoded[3]
# labels_encoded.shape

In [43]:
# Convert labels to label encoding -
labels = labels_df['class'].astype(str).to_numpy()  # Ensure all labels are strings
unique_labels = np.unique(labels)
print(f"Total Unique Labels are - {len(unique_labels)}")

Total Unique Labels are - 11

In [44]:
label_to_index = {label: index for index, label in enumerate(unique_labels)}
label_to_index

{'articulated_truck': 0,
 'bicycle': 1,
 'bus': 2,
 'car': 3,
 'motorcycle': 4,
 'motorized_vehicle': 5,
 'non-motorized_vehicle': 6,
 'pedestrian': 7,
 'pickup_truck': 8,
 'single_unit_truck': 9,
 'work_van': 10}

In [45]:
labels_encoded_int = np.array([label_to_index[label] for label in labels])
labels_encoded_int

array([ 8,  3,  3,  0,  3,  2,  2,  3,  3,  3,  3,  5,  3,  3,  2,  3,  0,
        3,  3,  8,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        8,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  2,  3,  3,  8,  0, 10,
        5,  3,  5,  3,  3,  3,  0,  3,  3,  3,  3,  3,  2,  2,  3,  5,  3,
        3,  3,  3,  5,  8,  3,  8,  3,  3,  8,  3,  3,  3,  3,  9,  9,  3,
        8,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  0,  3,  3,  3,  8,  3,
        3,  9,  3,  3,  8,  3,  3,  8,  8,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  5,  3, 10,  3,  3,  2,  3,  3,  3, 10,  8,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  5,  7,  3,  3,  5,  3,  8,  3,  3,
        8,  3,  3,  3,  3,  3,  5,  3,  8,  8, 10,  8,  8,  3,  8,  3,  3,
        3,  5,  3,  5,  8,  3,  5,  8,  8,  3,  3, 10,  0,  5,  3,  8,  3,
        3,  8,  3,  8,  3,  3,  5,  3,  3,  3,  8,  8,  3,  8, 10,  3,  3,
        8,  3,  8,  3,  3,  3,  3,  3,  3,  3,  3,  3,  5,  0,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  1,  3,  3,  8,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3, 10,  3,  5,  3,  3, 10,  3,  3,  3,  3,  3, 10,
        3,  3,  3,  5,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  5,  3,  3,  3,  3,  5,  3,  3,  3,  3,  3,  3,  3,
        2,  3,  3, 10,  3,  3,  3,  3,  3,  3,  3,  3,  0,  2,  3,  0,  3,
        3,  3,  8,  8,  3,  3,  3,  3,  8,  3,  3,  3,  3,  3,  3,  3,  2,
        3,  3,  8,  3,  2,  3,  3,  9,  3,  3,  8,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  0,  0,  3,  3,  3,  3,  3,  3,  3,
        2,  3,  3,  3,  8,  7,  1,  7,  7,  1, 10,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  5,  7,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  2,  3,  3,  3,  3,  3,  3,  5,  5,  5,  3,  8,  3,  3,
        3,  3, 10,  8, 10,  3,  3,  8,  3,  3,  6,  3,  3,  3,  3,  3,  3,
        3,  3, 10,  8,  5,  8,  5,  8,  3, 10,  3,  3,  8,  8,  5,  3,  3,
        3,  8,  2,  5,  5,  8,  8,  3,  3,  5,  3,  3,  8,  3,  3,  0,  3,
       10,  3,  3,  6,  3,  3,  3,  3,  9,  3,  3,  3,  3,  3,  1,  1,  3,
        3,  3,  3,  3,  3,  3,  3,  0,  7,  3,  7,  3,  3,  3,  3,  3,  3,
        5,  0,  9,  3,  5, 10,  3,  8,  3,  2,  3,  5,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  8,  3,  3,  7,  3,  3,  3,  3,  3,  3,  3,
        3,  9,  3,  3,  2,  3,  3,  3,  3,  3,  6,  9,  6,  3,  3,  5,  8,
        8,  8,  3,  3,  0,  3,  3,  3,  3,  3,  3,  8,  3,  8,  3,  3,  3,
        3,  3,  5,  3,  3,  0,  3,  8,  8,  3,  3,  3,  3,  3,  2,  3,  0,
        8,  3,  3,  0,  3,  8,  3,  3,  3,  3,  3,  3,  3,  3,  3,  1,  1,
        1,  3,  8,  8,  3,  3,  8,  3,  9,  3,  3,  3,  8,  3,  3,  3,  3,
        3,  3,  3,  3,  0, 10, 10,  2,  8,  3,  3,  3,  8,  8,  5,  3,  3,
        3,  3,  0,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  8,  3,  8,
        8,  3, 10,  8,  3,  3,  3,  5,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  7,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  7,  7,  5,  3,
        3,  7,  3,  5,  5,  3,  3,  5,  3,  3,  3,  8,  8,  3, 10,  3,  3,
        8,  3,  3,  8,  9,  6,  3,  8,  3,  3,  3,  3,  5,  9,  3,  3,  7,
       10,  3,  2,  5,  3,  3,  3,  3,  7,  3,  7,  8,  3,  3,  3,  0,  8,
        9,  0,  0,  5, 10,  0,  3,  3,  8,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  7,  7,  3,  2,  3,  3,  3,  3,  8,  3,  3,  5,  3,  3,  3,  3,
        3,  2,  3,  8,  3,  3,  3,  3,  5,  3,  3,  3,  9,  3,  3,  3,  0,
        8,  3,  5,  3,  5,  2,  3,  3,  8,  2,  5,  3,  0,  5,  8,  3,  3,
        3, 10,  3,  3,  3,  3,  2,  3,  2,  3, 10,  3,  3,  3,  2,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  5,  3,  3,  3,  7,  3,  3,  3,  3,  3,
        7,  3,  3,  3,  3,  3,  3,  3,  3,  4,  7,  3,  8,  3,  3,  3,  3,
        3,  5,  3,  8,  8,  3,  8,  3,  2,  8,  2,  9,  3,  3,  3,  3,  3,
        8,  3,  3,  1,  3,  8,  3,  3,  0, 10,  3,  3,  9,  5,  3,  3,  3,
        3,  3,  3,  5,  5,  3,  5,  3,  3,  8,  3,  3,  9,  3,  8,  0,  3,
        3,  9,  3,  3,  3,  3,  8,  3,  3,  5,  3,  8,  5,  3,  3,  8,  8,
        8,  8,  3,  9,  3,  1,  3,  1,  3,  8,  3,  5,  8,  3,  8,  3,  3,
        8,  3,  3,  3,  7, 10,  3,  3,  3,  3,  1,  3,  3,  3,  3,  7,  3,
        3,  3,  8,  3,  8,  3,  3,  3,  3,  3,  3,  3, 10,  8,  7,  3,  3,
        3,  8,  3,  8,  0,  8,  3,  3,  3,  3,  3,  8,  3,  3,  3,  3,  3,
        3,  3,  5,  3,  5,  3,  3,  3,  3,  5,  3,  0,  3, 10])

In [65]:
labels = np.array([label_to_index[label] for label in labels])

In [66]:
len(labels)

1000

In [49]:
len(bounding_boxes)

1000

In [48]:
labels_df.head()

   image_id              class  xmin  ymin  xmax  ymax
0  00000000       pickup_truck   213    34   255    50
1  00000000                car   194    78   273   122
2  00000000                car   155    27   183    35
3  00000000  articulated_truck    43    25   109    55
4  00000000                car   106    32   124    45

In [71]:
X_train, X_test, y_train, y_test, bbox_train, bbox_test = train_test_split(processed_images, labels, bounding_boxes, test_size=0.2, random_state=42)

# Creation of CNN Architecture

In [72]:
# Model Creation
def create_model(input_shape, num_classes):
    inputs = keras.Input(shape=input_shape)
    x = layers.Conv2D(32, (3, 3), activation='relu')(inputs)
    x = layers.MaxPooling2D((2, 2))(x)
    
    x = layers.Conv2D(64, (3, 3), activation='relu')(x)
    x = layers.MaxPooling2D((2, 2))(x)

    x = layers.Conv2D(64, (3, 3), activation='relu')(x)
    x = layers.Flatten()(x)
    
    x = layers.Dense(64, activation='relu')(x)

    vehicle_class = layers.Dense(num_classes, activation='softmax', name='vehicle_class')(x)

    bounding_box = layers.Dense(4, name='bounding_box')(x)
    model = keras.Model(inputs=inputs, outputs=[vehicle_class, bounding_box])
    return model

In [73]:
input_shape = processed_images[0].shape
num_classes = len(unique_labels)

In [74]:
model = create_model(input_shape, num_classes)

In [75]:
model.compile(optimizer='adam', loss={'vehicle_class': 'sparse_categorical_crossentropy', 'bounding_box': 'mse'}, 
                metrics={'vehicle_class': 'accuracy', 'bounding_box': 'mse'})

In [81]:
model.fit(X_train, {"vehicle_class":y_train, "bounding_box": bbox_train}, epochs=100, validation_data=(X_test, {"vehicle_class":y_test, "bounding_box": bbox_test}))

Epoch 1/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 31s 1s/step - bounding_box_loss: 32487.8105 - bounding_box_mse: 32487.8105 - loss: 32765.7168 - vehicle_class_accuracy: 0.0125 - vehicle_class_loss: 277.9120 - val_bounding_box_loss: 35440.6133 - val_bounding_box_mse: 33963.3086 - val_loss: 34109.8555 - val_vehicle_class_accuracy: 0.0100 - val_vehicle_class_loss: 137.0612
Epoch 2/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 33s 1s/step - bounding_box_loss: 29500.8730 - bounding_box_mse: 29500.8730 - loss: 29636.1719 - vehicle_class_accuracy: 0.3063 - vehicle_class_loss: 135.3043 - val_bounding_box_loss: 30575.9551 - val_bounding_box_mse: 29789.4727 - val_loss: 29906.8926 - val_vehicle_class_accuracy: 0.6850 - val_vehicle_class_loss: 104.8376
Epoch 3/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 33s 1s/step - bounding_box_loss: 27137.7598 - bounding_box_mse: 27137.7598 - loss: 27248.9473 - vehicle_class_accuracy: 0.5612 - vehicle_class_loss: 111.1857 - val_bounding_box_loss: 30252.7383 - val_bounding_box_mse: 30020.7246 - val_loss: 30128.2168 - val_vehicle_class_accuracy: 0.6850 - val_vehicle_class_loss: 95.9765
Epoch 4/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 29s 1s/step - bounding_box_loss: 27456.4004 - bounding_box_mse: 27456.4004 - loss: 27543.3203 - vehicle_class_accuracy: 0.5987 - vehicle_class_loss: 86.9195 - val_bounding_box_loss: 33295.2383 - val_bounding_box_mse: 33606.9180 - val_loss: 33692.7812 - val_vehicle_class_accuracy: 0.3400 - val_vehicle_class_loss: 76.8992
Epoch 5/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 27s 1s/step - bounding_box_loss: 26294.7422 - bounding_box_mse: 26294.7422 - loss: 26360.7773 - vehicle_class_accuracy: 0.5400 - vehicle_class_loss: 66.0376 - val_bounding_box_loss: 30402.2500 - val_bounding_box_mse: 30344.0527 - val_loss: 30406.3320 - val_vehicle_class_accuracy: 0.6400 - val_vehicle_class_loss: 55.6065
Epoch 6/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 27s 1s/step - bounding_box_loss: 26206.6699 - bounding_box_mse: 26206.6699 - loss: 26260.4121 - vehicle_class_accuracy: 0.4888 - vehicle_class_loss: 53.7455 - val_bounding_box_loss: 29465.3574 - val_bounding_box_mse: 29113.2148 - val_loss: 29158.9766 - val_vehicle_class_accuracy: 0.4600 - val_vehicle_class_loss: 41.0546
Epoch 7/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 27s 1s/step - bounding_box_loss: 24863.5918 - bounding_box_mse: 24863.5918 - loss: 24903.3516 - vehicle_class_accuracy: 0.5075 - vehicle_class_loss: 39.7659 - val_bounding_box_loss: 30048.6777 - val_bounding_box_mse: 29752.1895 - val_loss: 29783.9570 - val_vehicle_class_accuracy: 0.4600 - val_vehicle_class_loss: 28.5057
Epoch 8/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 27s 1s/step - bounding_box_loss: 24143.0625 - bounding_box_mse: 24143.0625 - loss: 24170.4258 - vehicle_class_accuracy: 0.4638 - vehicle_class_loss: 27.3614 - val_bounding_box_loss: 29195.4902 - val_bounding_box_mse: 28639.0547 - val_loss: 28654.7324 - val_vehicle_class_accuracy: 0.6150 - val_vehicle_class_loss: 13.9971
Epoch 9/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 29s 1s/step - bounding_box_loss: 22922.7422 - bounding_box_mse: 22922.7422 - loss: 22943.2383 - vehicle_class_accuracy: 0.4900 - vehicle_class_loss: 20.4939 - val_bounding_box_loss: 29481.9375 - val_bounding_box_mse: 28962.7207 - val_loss: 28975.7266 - val_vehicle_class_accuracy: 0.4250 - val_vehicle_class_loss: 12.1489
Epoch 10/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 32s 1s/step - bounding_box_loss: 22025.2598 - bounding_box_mse: 22025.2598 - loss: 22042.0059 - vehicle_class_accuracy: 0.4588 - vehicle_class_loss: 16.7421 - val_bounding_box_loss: 30970.1211 - val_bounding_box_mse: 29655.5879 - val_loss: 29670.7266 - val_vehicle_class_accuracy: 0.6150 - val_vehicle_class_loss: 13.8548
Epoch 11/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 32s 1s/step - bounding_box_loss: 21424.4219 - bounding_box_mse: 21424.4219 - loss: 21442.3652 - vehicle_class_accuracy: 0.4500 - vehicle_class_loss: 17.9418 - val_bounding_box_loss: 31981.1113 - val_bounding_box_mse: 30836.4922 - val_loss: 30855.6953 - val_vehicle_class_accuracy: 0.3600 - val_vehicle_class_loss: 18.4114
Epoch 12/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 29s 1s/step - bounding_box_loss: 21152.6895 - bounding_box_mse: 21152.6895 - loss: 21172.1445 - vehicle_class_accuracy: 0.4875 - vehicle_class_loss: 19.4522 - val_bounding_box_loss: 30523.3066 - val_bounding_box_mse: 29385.5000 - val_loss: 29400.6621 - val_vehicle_class_accuracy: 0.6050 - val_vehicle_class_loss: 13.5396
Epoch 13/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 28s 1s/step - bounding_box_loss: 20651.4844 - bounding_box_mse: 20651.4844 - loss: 20668.3223 - vehicle_class_accuracy: 0.4850 - vehicle_class_loss: 16.8371 - val_bounding_box_loss: 30692.9473 - val_bounding_box_mse: 29196.0723 - val_loss: 29206.9023 - val_vehicle_class_accuracy: 0.5150 - val_vehicle_class_loss: 10.0454
Epoch 14/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 29s 1s/step - bounding_box_loss: 21095.4727 - bounding_box_mse: 21095.4727 - loss: 21113.1699 - vehicle_class_accuracy: 0.4712 - vehicle_class_loss: 17.6972 - val_bounding_box_loss: 31989.0000 - val_bounding_box_mse: 31093.2891 - val_loss: 31110.7754 - val_vehicle_class_accuracy: 0.3400 - val_vehicle_class_loss: 16.0760
Epoch 15/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 31s 1s/step - bounding_box_loss: 20392.1484 - bounding_box_mse: 20392.1484 - loss: 20410.8555 - vehicle_class_accuracy: 0.4725 - vehicle_class_loss: 18.7104 - val_bounding_box_loss: 33416.9922 - val_bounding_box_mse: 31673.0273 - val_loss: 31683.4199 - val_vehicle_class_accuracy: 0.5400 - val_vehicle_class_loss: 9.5383
Epoch 16/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 45s 1s/step - bounding_box_loss: 20138.2715 - bounding_box_mse: 20138.2715 - loss: 20153.1680 - vehicle_class_accuracy: 0.4450 - vehicle_class_loss: 14.8983 - val_bounding_box_loss: 33162.5547 - val_bounding_box_mse: 31689.4043 - val_loss: 31701.8672 - val_vehicle_class_accuracy: 0.5600 - val_vehicle_class_loss: 11.5053
Epoch 17/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 31s 1s/step - bounding_box_loss: 19381.6191 - bounding_box_mse: 19381.6191 - loss: 19395.7871 - vehicle_class_accuracy: 0.5000 - vehicle_class_loss: 14.1688 - val_bounding_box_loss: 31835.7949 - val_bounding_box_mse: 30297.4531 - val_loss: 30307.3594 - val_vehicle_class_accuracy: 0.4950 - val_vehicle_class_loss: 9.1389
Epoch 18/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 32s 1s/step - bounding_box_loss: 19740.7930 - bounding_box_mse: 19740.7930 - loss: 19755.2480 - vehicle_class_accuracy: 0.4737 - vehicle_class_loss: 14.4521 - val_bounding_box_loss: 29855.4102 - val_bounding_box_mse: 28711.3320 - val_loss: 28723.0703 - val_vehicle_class_accuracy: 0.6200 - val_vehicle_class_loss: 10.4827
Epoch 19/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 32s 1s/step - bounding_box_loss: 20014.8203 - bounding_box_mse: 20014.8203 - loss: 20029.1504 - vehicle_class_accuracy: 0.4988 - vehicle_class_loss: 14.3272 - val_bounding_box_loss: 30939.4160 - val_bounding_box_mse: 30229.3223 - val_loss: 30241.1133 - val_vehicle_class_accuracy: 0.4950 - val_vehicle_class_loss: 10.9033
Epoch 20/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 31s 1s/step - bounding_box_loss: 18730.5801 - bounding_box_mse: 18730.5801 - loss: 18745.2031 - vehicle_class_accuracy: 0.4487 - vehicle_class_loss: 14.6242 - val_bounding_box_loss: 31060.8574 - val_bounding_box_mse: 30608.0742 - val_loss: 30619.5801 - val_vehicle_class_accuracy: 0.5750 - val_vehicle_class_loss: 10.4429
Epoch 21/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 30s 1s/step - bounding_box_loss: 18650.4102 - bounding_box_mse: 18650.4102 - loss: 18663.8008 - vehicle_class_accuracy: 0.4663 - vehicle_class_loss: 13.3906 - val_bounding_box_loss: 30922.6348 - val_bounding_box_mse: 29379.7500 - val_loss: 29388.5332 - val_vehicle_class_accuracy: 0.5600 - val_vehicle_class_loss: 8.0864
Epoch 22/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 31s 1s/step - bounding_box_loss: 18321.9844 - bounding_box_mse: 18321.9844 - loss: 18334.5742 - vehicle_class_accuracy: 0.4850 - vehicle_class_loss: 12.5914 - val_bounding_box_loss: 32992.5938 - val_bounding_box_mse: 31119.1797 - val_loss: 31128.4004 - val_vehicle_class_accuracy: 0.5650 - val_vehicle_class_loss: 8.4348
Epoch 23/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 33s 1s/step - bounding_box_loss: 19247.3379 - bounding_box_mse: 19247.3379 - loss: 19259.7656 - vehicle_class_accuracy: 0.4625 - vehicle_class_loss: 12.4288 - val_bounding_box_loss: 34980.9414 - val_bounding_box_mse: 33361.7539 - val_loss: 33372.7930 - val_vehicle_class_accuracy: 0.5400 - val_vehicle_class_loss: 9.9793
Epoch 24/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 31s 1s/step - bounding_box_loss: 18898.0020 - bounding_box_mse: 18898.0020 - loss: 18911.5410 - vehicle_class_accuracy: 0.4563 - vehicle_class_loss: 13.5423 - val_bounding_box_loss: 31730.9492 - val_bounding_box_mse: 30251.4434 - val_loss: 30264.2656 - val_vehicle_class_accuracy: 0.6750 - val_vehicle_class_loss: 11.4505
Epoch 25/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 29s 1s/step - bounding_box_loss: 18164.9668 - bounding_box_mse: 18164.9668 - loss: 18177.8867 - vehicle_class_accuracy: 0.4775 - vehicle_class_loss: 12.9177 - val_bounding_box_loss: 32791.0859 - val_bounding_box_mse: 31257.4492 - val_loss: 31267.5605 - val_vehicle_class_accuracy: 0.6400 - val_vehicle_class_loss: 9.1677
Epoch 26/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 31s 1s/step - bounding_box_loss: 18285.0156 - bounding_box_mse: 18285.0156 - loss: 18296.5156 - vehicle_class_accuracy: 0.4913 - vehicle_class_loss: 11.4970 - val_bounding_box_loss: 30769.2773 - val_bounding_box_mse: 29586.1230 - val_loss: 29593.6543 - val_vehicle_class_accuracy: 0.6000 - val_vehicle_class_loss: 6.8402
Epoch 27/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 31s 1s/step - bounding_box_loss: 18052.6230 - bounding_box_mse: 18052.6230 - loss: 18062.6367 - vehicle_class_accuracy: 0.4725 - vehicle_class_loss: 10.0123 - val_bounding_box_loss: 32837.0391 - val_bounding_box_mse: 31308.9121 - val_loss: 31316.4609 - val_vehicle_class_accuracy: 0.5100 - val_vehicle_class_loss: 7.0301
Epoch 28/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 29s 1s/step - bounding_box_loss: 18584.3477 - bounding_box_mse: 18584.3477 - loss: 18594.3086 - vehicle_class_accuracy: 0.4787 - vehicle_class_loss: 9.9642 - val_bounding_box_loss: 31634.1914 - val_bounding_box_mse: 30877.3594 - val_loss: 30885.8945 - val_vehicle_class_accuracy: 0.6550 - val_vehicle_class_loss: 7.6254
Epoch 29/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 29s 1s/step - bounding_box_loss: 18009.2246 - bounding_box_mse: 18009.2246 - loss: 18018.6816 - vehicle_class_accuracy: 0.4888 - vehicle_class_loss: 9.4577 - val_bounding_box_loss: 31081.9043 - val_bounding_box_mse: 29638.9141 - val_loss: 29645.6758 - val_vehicle_class_accuracy: 0.5000 - val_vehicle_class_loss: 6.1937
Epoch 30/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 31s 1s/step - bounding_box_loss: 17763.8672 - bounding_box_mse: 17763.8672 - loss: 17772.7578 - vehicle_class_accuracy: 0.4950 - vehicle_class_loss: 8.8912 - val_bounding_box_loss: 30614.2305 - val_bounding_box_mse: 29329.3496 - val_loss: 29335.7520 - val_vehicle_class_accuracy: 0.6250 - val_vehicle_class_loss: 5.7731
Epoch 31/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 31s 1s/step - bounding_box_loss: 17680.5195 - bounding_box_mse: 17680.5195 - loss: 17688.9043 - vehicle_class_accuracy: 0.4600 - vehicle_class_loss: 8.3810 - val_bounding_box_loss: 31098.0352 - val_bounding_box_mse: 29645.8418 - val_loss: 29651.7949 - val_vehicle_class_accuracy: 0.5600 - val_vehicle_class_loss: 5.4056
Epoch 32/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 30s 1s/step - bounding_box_loss: 17536.4844 - bounding_box_mse: 17536.4844 - loss: 17545.0859 - vehicle_class_accuracy: 0.5063 - vehicle_class_loss: 8.6015 - val_bounding_box_loss: 31944.8652 - val_bounding_box_mse: 30836.1641 - val_loss: 30844.6855 - val_vehicle_class_accuracy: 0.3600 - val_vehicle_class_loss: 8.1881
Epoch 33/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 30s 1s/step - bounding_box_loss: 18305.7793 - bounding_box_mse: 18305.7793 - loss: 18315.4961 - vehicle_class_accuracy: 0.4450 - vehicle_class_loss: 9.7168 - val_bounding_box_loss: 33675.0547 - val_bounding_box_mse: 33330.2891 - val_loss: 33340.0039 - val_vehicle_class_accuracy: 0.6700 - val_vehicle_class_loss: 8.6743
Epoch 34/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 31s 1s/step - bounding_box_loss: 18153.5723 - bounding_box_mse: 18153.5723 - loss: 18162.0566 - vehicle_class_accuracy: 0.4975 - vehicle_class_loss: 8.4880 - val_bounding_box_loss: 31375.1152 - val_bounding_box_mse: 30424.4629 - val_loss: 30430.3398 - val_vehicle_class_accuracy: 0.6050 - val_vehicle_class_loss: 5.4660
Epoch 35/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 31s 1s/step - bounding_box_loss: 18431.8594 - bounding_box_mse: 18431.8594 - loss: 18441.7969 - vehicle_class_accuracy: 0.4588 - vehicle_class_loss: 9.9390 - val_bounding_box_loss: 33727.0820 - val_bounding_box_mse: 31383.7949 - val_loss: 31394.4082 - val_vehicle_class_accuracy: 0.6500 - val_vehicle_class_loss: 9.4815
Epoch 36/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 31s 1s/step - bounding_box_loss: 18676.5371 - bounding_box_mse: 18676.5371 - loss: 18687.7441 - vehicle_class_accuracy: 0.4437 - vehicle_class_loss: 11.2080 - val_bounding_box_loss: 32507.6211 - val_bounding_box_mse: 31663.7520 - val_loss: 31671.4824 - val_vehicle_class_accuracy: 0.3550 - val_vehicle_class_loss: 7.3982
Epoch 37/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 30s 1s/step - bounding_box_loss: 17577.6133 - bounding_box_mse: 17577.6133 - loss: 17586.2109 - vehicle_class_accuracy: 0.4825 - vehicle_class_loss: 8.5983 - val_bounding_box_loss: 31404.4277 - val_bounding_box_mse: 29893.2324 - val_loss: 29900.4316 - val_vehicle_class_accuracy: 0.3000 - val_vehicle_class_loss: 7.1094
Epoch 38/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 30s 1s/step - bounding_box_loss: 18517.7461 - bounding_box_mse: 18517.7461 - loss: 18525.3945 - vehicle_class_accuracy: 0.4625 - vehicle_class_loss: 7.6472 - val_bounding_box_loss: 32986.8906 - val_bounding_box_mse: 31281.0000 - val_loss: 31287.3027 - val_vehicle_class_accuracy: 0.3200 - val_vehicle_class_loss: 6.0461
Epoch 39/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 29s 1s/step - bounding_box_loss: 18169.0742 - bounding_box_mse: 18169.0742 - loss: 18175.8301 - vehicle_class_accuracy: 0.4762 - vehicle_class_loss: 6.7540 - val_bounding_box_loss: 32659.0781 - val_bounding_box_mse: 31605.7793 - val_loss: 31612.6543 - val_vehicle_class_accuracy: 0.4600 - val_vehicle_class_loss: 6.5112
Epoch 40/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 28s 1s/step - bounding_box_loss: 17339.6621 - bounding_box_mse: 17339.6621 - loss: 17346.6973 - vehicle_class_accuracy: 0.5013 - vehicle_class_loss: 7.0324 - val_bounding_box_loss: 33993.4805 - val_bounding_box_mse: 32173.3047 - val_loss: 32181.4941 - val_vehicle_class_accuracy: 0.2250 - val_vehicle_class_loss: 8.0329
Epoch 41/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 31s 1s/step - bounding_box_loss: 17713.3203 - bounding_box_mse: 17713.3203 - loss: 17719.8477 - vehicle_class_accuracy: 0.5038 - vehicle_class_loss: 6.5236 - val_bounding_box_loss: 30572.9004 - val_bounding_box_mse: 29474.3848 - val_loss: 29481.1074 - val_vehicle_class_accuracy: 0.2550 - val_vehicle_class_loss: 6.6326
Epoch 42/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 34s 1s/step - bounding_box_loss: 18052.3984 - bounding_box_mse: 18052.3984 - loss: 18059.2793 - vehicle_class_accuracy: 0.5100 - vehicle_class_loss: 6.8822 - val_bounding_box_loss: 32140.3750 - val_bounding_box_mse: 31175.8398 - val_loss: 31180.9531 - val_vehicle_class_accuracy: 0.6250 - val_vehicle_class_loss: 4.5872
Epoch 43/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 33s 1s/step - bounding_box_loss: 17409.3242 - bounding_box_mse: 17409.3242 - loss: 17416.0176 - vehicle_class_accuracy: 0.4625 - vehicle_class_loss: 6.6930 - val_bounding_box_loss: 32658.9336 - val_bounding_box_mse: 32309.7598 - val_loss: 32316.9043 - val_vehicle_class_accuracy: 0.6600 - val_vehicle_class_loss: 6.3849
Epoch 44/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 32s 1s/step - bounding_box_loss: 16955.3691 - bounding_box_mse: 16955.3691 - loss: 16961.8496 - vehicle_class_accuracy: 0.4737 - vehicle_class_loss: 6.4799 - val_bounding_box_loss: 31428.8867 - val_bounding_box_mse: 30524.2500 - val_loss: 30529.3906 - val_vehicle_class_accuracy: 0.6650 - val_vehicle_class_loss: 4.5954
Epoch 45/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 38s 1s/step - bounding_box_loss: 16791.3516 - bounding_box_mse: 16791.3516 - loss: 16796.8008 - vehicle_class_accuracy: 0.4938 - vehicle_class_loss: 5.4476 - val_bounding_box_loss: 32223.2012 - val_bounding_box_mse: 30864.9141 - val_loss: 30870.5605 - val_vehicle_class_accuracy: 0.6400 - val_vehicle_class_loss: 5.0456
Epoch 46/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 29s 1s/step - bounding_box_loss: 16921.3926 - bounding_box_mse: 16921.3926 - loss: 16927.2461 - vehicle_class_accuracy: 0.4900 - vehicle_class_loss: 5.8509 - val_bounding_box_loss: 30418.0098 - val_bounding_box_mse: 29608.3477 - val_loss: 29612.4766 - val_vehicle_class_accuracy: 0.4150 - val_vehicle_class_loss: 3.9284
Epoch 47/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 31s 1s/step - bounding_box_loss: 16758.3828 - bounding_box_mse: 16758.3828 - loss: 16763.7070 - vehicle_class_accuracy: 0.5375 - vehicle_class_loss: 5.3227 - val_bounding_box_loss: 33907.2305 - val_bounding_box_mse: 32747.8125 - val_loss: 32752.0859 - val_vehicle_class_accuracy: 0.4400 - val_vehicle_class_loss: 4.0286
Epoch 48/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 30s 1s/step - bounding_box_loss: 17007.1758 - bounding_box_mse: 17007.1758 - loss: 17011.7559 - vehicle_class_accuracy: 0.5375 - vehicle_class_loss: 4.5810 - val_bounding_box_loss: 31895.6738 - val_bounding_box_mse: 30571.3867 - val_loss: 30574.9570 - val_vehicle_class_accuracy: 0.6100 - val_vehicle_class_loss: 3.2015
Epoch 49/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 30s 1s/step - bounding_box_loss: 16800.3555 - bounding_box_mse: 16800.3555 - loss: 16806.6348 - vehicle_class_accuracy: 0.4913 - vehicle_class_loss: 6.2803 - val_bounding_box_loss: 30793.8926 - val_bounding_box_mse: 29496.0332 - val_loss: 29500.7480 - val_vehicle_class_accuracy: 0.5950 - val_vehicle_class_loss: 4.2671
Epoch 50/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 30s 1s/step - bounding_box_loss: 16916.6445 - bounding_box_mse: 16916.6445 - loss: 16921.8320 - vehicle_class_accuracy: 0.5350 - vehicle_class_loss: 5.1867 - val_bounding_box_loss: 32130.0293 - val_bounding_box_mse: 31353.7305 - val_loss: 31358.2207 - val_vehicle_class_accuracy: 0.6300 - val_vehicle_class_loss: 4.0248
Epoch 51/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 32s 1s/step - bounding_box_loss: 16901.7207 - bounding_box_mse: 16901.7207 - loss: 16906.5742 - vehicle_class_accuracy: 0.4875 - vehicle_class_loss: 4.8538 - val_bounding_box_loss: 31677.4414 - val_bounding_box_mse: 30567.4043 - val_loss: 30571.3008 - val_vehicle_class_accuracy: 0.6700 - val_vehicle_class_loss: 3.4995
Epoch 52/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 31s 1s/step - bounding_box_loss: 16625.7207 - bounding_box_mse: 16625.7207 - loss: 16630.4922 - vehicle_class_accuracy: 0.5075 - vehicle_class_loss: 4.7690 - val_bounding_box_loss: 32054.6621 - val_bounding_box_mse: 30828.0547 - val_loss: 30832.9121 - val_vehicle_class_accuracy: 0.2300 - val_vehicle_class_loss: 4.5480
Epoch 53/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 30s 1s/step - bounding_box_loss: 16890.3809 - bounding_box_mse: 16890.3809 - loss: 16894.9648 - vehicle_class_accuracy: 0.5050 - vehicle_class_loss: 4.5851 - val_bounding_box_loss: 32801.4922 - val_bounding_box_mse: 32294.7441 - val_loss: 32297.9844 - val_vehicle_class_accuracy: 0.5500 - val_vehicle_class_loss: 2.9527
Epoch 54/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 30s 1s/step - bounding_box_loss: 16661.8770 - bounding_box_mse: 16661.8770 - loss: 16666.2012 - vehicle_class_accuracy: 0.4988 - vehicle_class_loss: 4.3236 - val_bounding_box_loss: 32395.9746 - val_bounding_box_mse: 31255.1953 - val_loss: 31259.2676 - val_vehicle_class_accuracy: 0.6300 - val_vehicle_class_loss: 3.6440
Epoch 55/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 30s 1s/step - bounding_box_loss: 16677.8516 - bounding_box_mse: 16677.8516 - loss: 16682.5684 - vehicle_class_accuracy: 0.5587 - vehicle_class_loss: 4.7181 - val_bounding_box_loss: 31353.2949 - val_bounding_box_mse: 30414.9766 - val_loss: 30418.4004 - val_vehicle_class_accuracy: 0.5250 - val_vehicle_class_loss: 3.1625
Epoch 56/100

## Module Evaluation

In [82]:
model.evaluate(X_test, {"vehicle_class": y_test, "bounding_box": bbox_test}, verbose=2)

7/7 - 2s - 284ms/step - bounding_box_loss: 30907.3535 - bounding_box_mse: 30019.3379 - loss: 30021.4922 - vehicle_class_accuracy: 0.5500 - vehicle_class_loss: 1.9751

[30021.4921875,
 1.9750902652740479,
 30907.353515625,
 30019.337890625,
 0.550000011920929]

In [83]:
sample_image = X_test[:5]
predictions = model.predict(sample_image)
predicted_bounding_boxes = predictions[1]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step